modLoader = "javafml" #mandatory
loaderVersion = "2" #mandatory
license = "MI"
[[mods]] #mandatory
modId = "slimed" #mandatory
version = "1.0.0 DEV" #mandatory
displayName = "Slimed" #mandatory
authors = "Tebreca" #optional
description = '''Slimed, gooey crafting'''
